/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avrilco.siac;

/**
 *
 * @author DELL
 */
public class atencionCliente extends javax.swing.JFrame {

    /**
     * Creates new form atencionCliente
     */
    public atencionCliente() {
        initComponents();
        //Hacemos que aparezca en el centro de la pantalla
        ChangeLocation();
    }
    
    private void ChangeLocation(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSolicitudCreditos = new javax.swing.JPanel();
        tblpSolicitudCreditoProspecto = new javax.swing.JTabbedPane();
        pnlGeneralProspecto = new javax.swing.JPanel();
        pnlSolicitantesProspecto = new javax.swing.JPanel();
        lblNombreProspecto = new javax.swing.JLabel();
        lblDuiProspecto = new javax.swing.JLabel();
        lblFechaNacimientoProspecto = new javax.swing.JLabel();
        txtNombreSolicitanteProspecto = new javax.swing.JTextField();
        txtDuiSolicitanteProspecto = new javax.swing.JTextField();
        lblEmpresaProspecto = new javax.swing.JLabel();
        cbxEsEmpleadoProspecto = new javax.swing.JCheckBox();
        lblTelefonoProspecto = new javax.swing.JLabel();
        lblSalarioProspecto = new javax.swing.JLabel();
        txtEmpresaProspecto = new javax.swing.JTextField();
        txtTelefonoProspecto = new javax.swing.JTextField();
        txtSalarioProspecto = new javax.swing.JTextField();
        lblTiempoLaboradoProspecto = new javax.swing.JLabel();
        txtTiempoLaboradoProspecto = new javax.swing.JTextField();
        lblDireccionProspecto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDireccionProspecto = new javax.swing.JTextArea();
        lblCargoProspecto = new javax.swing.JLabel();
        txtCargoProspecto = new javax.swing.JTextField();
        cbxEsPencionadoProspecto = new javax.swing.JCheckBox();
        lblGradoDiscapacidadProspecto = new javax.swing.JLabel();
        lblMontoPencionProspecto = new javax.swing.JLabel();
        txtGradoDiscapacidadProspecto = new javax.swing.JTextField();
        txtMontoPensionProspecto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblmontoProspecto = new javax.swing.JLabel();
        lblPlazoMesesProspecto = new javax.swing.JLabel();
        lblFormaPagoProspecto = new javax.swing.JLabel();
        lblTipoGarantiaProspecto = new javax.swing.JLabel();
        txtMontoProspecto = new javax.swing.JTextField();
        txtPlazoMesesPropuesta = new javax.swing.JTextField();
        txtFormaPagoProspecto = new javax.swing.JTextField();
        txtTipoGarantiaProspecto = new javax.swing.JTextField();
        dcFechaNacimientoProspecto = new com.toedter.calendar.JDateChooser();
        pnlCriteriosBusquedaProspecto = new javax.swing.JPanel();
        pnlReferenciasProspecto = new javax.swing.JPanel();
        pnlReferenciasPersonalesProspecto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReferenciasPersonalesProspecto = new javax.swing.JTable();
        pnlReferenciaBancariasProspecto = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReferenciasBancariasProspecto = new javax.swing.JTable();
        pnlReferenciaInternaProspecto = new javax.swing.JPanel();
        lblTipoPrestamoProspecto = new javax.swing.JLabel();
        txtTipoPrestamoProspecto = new javax.swing.JTextField();
        lblMontoReferenciaProspecto = new javax.swing.JLabel();
        txtMontoReferenciaProspecto = new javax.swing.JTextField();
        pnlIngresosEgresosProspecto = new javax.swing.JPanel();
        lblIngresosProspecto = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblIngresosProspecto = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEgresosProspectos = new javax.swing.JTable();
        lblEgresosProspecto = new javax.swing.JLabel();
        btnGuardarProspecto = new javax.swing.JButton();
        pnlSolicitudAhorro = new javax.swing.JPanel();
        pnlSolicitanteAhorro = new javax.swing.JPanel();
        lblNombreAhorro = new javax.swing.JLabel();
        txtNombreAhorro = new javax.swing.JTextField();
        lblDUIAhorro = new javax.swing.JLabel();
        txtDUIAhorro = new javax.swing.JTextField();
        lblFechaNacAhorro = new javax.swing.JLabel();
        lblTelefonoAhorro = new javax.swing.JLabel();
        txtTelefonoAhorro = new javax.swing.JTextField();
        lblCuentaAhorro = new javax.swing.JLabel();
        txtCuentaAhorro = new javax.swing.JTextField();
        lblTasaAhorro = new javax.swing.JLabel();
        lblTipoDocumentoAhorro = new javax.swing.JLabel();
        txtTasaAhorro = new javax.swing.JTextField();
        cboTipoDocumentoAhorro = new javax.swing.JComboBox<>();
        cboTipoCuentaAhorro = new javax.swing.JComboBox<>();
        lblTipoCuentaAhorro = new javax.swing.JLabel();
        lblFechaNacAhorro1 = new javax.swing.JLabel();
        lblMontoAhorro = new javax.swing.JLabel();
        txtMontoAhorro = new javax.swing.JTextField();
        lblBeneficiarioAhorro = new javax.swing.JLabel();
        scrBeneficiarioAhorro = new javax.swing.JScrollPane();
        txaBeneficiarioAhorro = new javax.swing.JTextArea();
        btnGuardarAhorro = new javax.swing.JButton();
        dcFechaAperturaAhorro = new com.toedter.calendar.JDateChooser();
        dcFechaCancelacionAhorro = new com.toedter.calendar.JDateChooser();
        scrSolicitudAhorro = new javax.swing.JScrollPane();
        tblSolicitudAhorro = new javax.swing.JTable();
        pnlBusquedaAhorro = new javax.swing.JPanel();
        txtBusquedaNombreAhorro = new javax.swing.JTextField();
        lblBusquedaNombreAhorro = new javax.swing.JLabel();
        btnBusquedaBuscarAhorro = new javax.swing.JButton();
        lblBuscarPorAhorro = new javax.swing.JLabel();
        cboBuscarPorAhorro = new javax.swing.JComboBox<>();
        lblBuscarFechaInicioAhorro = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblBuscarFechaFinAhorro = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lblNombrePantalla = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnlBarraEstado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Mora = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atención de clientes - SIAC");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1270, 645));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Calendario de Pagos", jPanel2);

        pnlSolicitantesProspecto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblNombreProspecto.setText("Nombre:");

        lblDuiProspecto.setText("DUI:");

        lblFechaNacimientoProspecto.setText("fecha de nacimiento:");

        lblEmpresaProspecto.setText("Empresa:");

        cbxEsEmpleadoProspecto.setText("Es Empleado");

        lblTelefonoProspecto.setText("Telefono:");

        lblSalarioProspecto.setText("Salario:");

        txtEmpresaProspecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaProspectoActionPerformed(evt);
            }
        });

        txtTelefonoProspecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProspectoActionPerformed(evt);
            }
        });

        lblTiempoLaboradoProspecto.setText("Tiempo laborado:");

        lblDireccionProspecto.setText("Direccion:");

        txaDireccionProspecto.setColumns(20);
        txaDireccionProspecto.setRows(5);
        jScrollPane3.setViewportView(txaDireccionProspecto);

        lblCargoProspecto.setText("Cargo:");

        cbxEsPencionadoProspecto.setText("Es pencionado");

        lblGradoDiscapacidadProspecto.setText("Grado de Discapacidad:");

        lblMontoPencionProspecto.setText("Monto pension:");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestamo"));

        lblmontoProspecto.setText("monto:");

        lblPlazoMesesProspecto.setText("Plazo en meses:");

        lblFormaPagoProspecto.setText("Forma de pago:");

        lblTipoGarantiaProspecto.setText("Tipo de garantia:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblPlazoMesesProspecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlazoMesesPropuesta))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblFormaPagoProspecto)
                        .addGap(10, 10, 10)
                        .addComponent(txtFormaPagoProspecto))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblmontoProspecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblTipoGarantiaProspecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoGarantiaProspecto)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmontoProspecto)
                    .addComponent(txtMontoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlazoMesesProspecto)
                    .addComponent(txtPlazoMesesPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagoProspecto)
                    .addComponent(txtFormaPagoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoGarantiaProspecto)
                    .addComponent(txtTipoGarantiaProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSolicitantesProspectoLayout = new javax.swing.GroupLayout(pnlSolicitantesProspecto);
        pnlSolicitantesProspecto.setLayout(pnlSolicitantesProspectoLayout);
        pnlSolicitantesProspectoLayout.setHorizontalGroup(
            pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNombreProspecto)
                                .addComponent(lblDuiProspecto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDuiSolicitanteProspecto)
                                .addComponent(txtNombreSolicitanteProspecto)))
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addComponent(lblSalarioProspecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSalarioProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(lblTiempoLaboradoProspecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTiempoLaboradoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addComponent(lblEmpresaProspecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpresaProspecto))
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addComponent(lblTelefonoProspecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTelefonoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addComponent(lblCargoProspecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCargoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                            .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFechaNacimientoProspecto)
                                .addComponent(cbxEsEmpleadoProspecto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcFechaNacimientoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                        .addComponent(lblDireccionProspecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitantesProspectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                                .addComponent(lblMontoPencionProspecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoPensionProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxEsPencionadoProspecto)
                            .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                                .addComponent(lblGradoDiscapacidadProspecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGradoDiscapacidadProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSolicitantesProspectoLayout.setVerticalGroup(
            pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitantesProspectoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitantesProspectoLayout.createSequentialGroup()
                        .addComponent(cbxEsPencionadoProspecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGradoDiscapacidadProspecto)
                            .addComponent(txtGradoDiscapacidadProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontoPencionProspecto)
                            .addComponent(txtMontoPensionProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitantesProspectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreSolicitanteProspecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreProspecto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDuiSolicitanteProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDuiProspecto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFechaNacimientoProspecto))
                            .addComponent(dcFechaNacimientoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEsEmpleadoProspecto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresaProspecto)
                    .addComponent(txtEmpresaProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoProspecto)
                    .addComponent(txtTelefonoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSolicitantesProspectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSalarioProspecto)
                            .addComponent(txtSalarioProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiempoLaboradoProspecto)
                            .addComponent(txtTiempoLaboradoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCargoProspecto)
                            .addComponent(txtCargoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSolicitantesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionProspecto)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pnlCriteriosBusquedaProspecto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        javax.swing.GroupLayout pnlCriteriosBusquedaProspectoLayout = new javax.swing.GroupLayout(pnlCriteriosBusquedaProspecto);
        pnlCriteriosBusquedaProspecto.setLayout(pnlCriteriosBusquedaProspectoLayout);
        pnlCriteriosBusquedaProspectoLayout.setHorizontalGroup(
            pnlCriteriosBusquedaProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        pnlCriteriosBusquedaProspectoLayout.setVerticalGroup(
            pnlCriteriosBusquedaProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlGeneralProspectoLayout = new javax.swing.GroupLayout(pnlGeneralProspecto);
        pnlGeneralProspecto.setLayout(pnlGeneralProspectoLayout);
        pnlGeneralProspectoLayout.setHorizontalGroup(
            pnlGeneralProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeneralProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCriteriosBusquedaProspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSolicitantesProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlGeneralProspectoLayout.setVerticalGroup(
            pnlGeneralProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralProspectoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlGeneralProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCriteriosBusquedaProspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSolicitantesProspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblpSolicitudCreditoProspecto.addTab("General", pnlGeneralProspecto);

        pnlReferenciasPersonalesProspecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Personales y familiares"));

        tblReferenciasPersonalesProspecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Telefono", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblReferenciasPersonalesProspecto);

        javax.swing.GroupLayout pnlReferenciasPersonalesProspectoLayout = new javax.swing.GroupLayout(pnlReferenciasPersonalesProspecto);
        pnlReferenciasPersonalesProspecto.setLayout(pnlReferenciasPersonalesProspectoLayout);
        pnlReferenciasPersonalesProspectoLayout.setHorizontalGroup(
            pnlReferenciasPersonalesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReferenciasPersonalesProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReferenciasPersonalesProspectoLayout.setVerticalGroup(
            pnlReferenciasPersonalesProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciasPersonalesProspectoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlReferenciaBancariasProspecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Bancarias"));

        tblReferenciasBancariasProspecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo de Cuenta", "Numero de Cuenta", "Prestamo Anterior"
            }
        ));
        jScrollPane4.setViewportView(tblReferenciasBancariasProspecto);

        javax.swing.GroupLayout pnlReferenciaBancariasProspectoLayout = new javax.swing.GroupLayout(pnlReferenciaBancariasProspecto);
        pnlReferenciaBancariasProspecto.setLayout(pnlReferenciaBancariasProspectoLayout);
        pnlReferenciaBancariasProspectoLayout.setHorizontalGroup(
            pnlReferenciaBancariasProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciaBancariasProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        pnlReferenciaBancariasProspectoLayout.setVerticalGroup(
            pnlReferenciaBancariasProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciaBancariasProspectoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pnlReferenciaInternaProspecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Internas"));

        lblTipoPrestamoProspecto.setText("tipo de prestamo:");

        lblMontoReferenciaProspecto.setText("Monto:");

        txtMontoReferenciaProspecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoReferenciaProspectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReferenciaInternaProspectoLayout = new javax.swing.GroupLayout(pnlReferenciaInternaProspecto);
        pnlReferenciaInternaProspecto.setLayout(pnlReferenciaInternaProspectoLayout);
        pnlReferenciaInternaProspectoLayout.setHorizontalGroup(
            pnlReferenciaInternaProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciaInternaProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoPrestamoProspecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoPrestamoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblMontoReferenciaProspecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoReferenciaProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReferenciaInternaProspectoLayout.setVerticalGroup(
            pnlReferenciaInternaProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciaInternaProspectoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlReferenciaInternaProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPrestamoProspecto)
                    .addComponent(txtTipoPrestamoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoReferenciaProspecto)
                    .addComponent(txtMontoReferenciaProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlReferenciasProspectoLayout = new javax.swing.GroupLayout(pnlReferenciasProspecto);
        pnlReferenciasProspecto.setLayout(pnlReferenciasProspectoLayout);
        pnlReferenciasProspectoLayout.setHorizontalGroup(
            pnlReferenciasProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciasProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReferenciasProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReferenciasPersonalesProspecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReferenciaBancariasProspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReferenciaInternaProspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlReferenciasProspectoLayout.setVerticalGroup(
            pnlReferenciasProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferenciasProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReferenciasPersonalesProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlReferenciaBancariasProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReferenciaInternaProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblpSolicitudCreditoProspecto.addTab("Referencias", pnlReferenciasProspecto);

        lblIngresosProspecto.setText("Ingresos");

        tblIngresosProspecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "parentesco", "nombre", "monto", "rason"
            }
        ));
        jScrollPane5.setViewportView(tblIngresosProspecto);

        tblEgresosProspectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "rason", "monto"
            }
        ));
        jScrollPane6.setViewportView(tblEgresosProspectos);

        lblEgresosProspecto.setText("Egresos");

        javax.swing.GroupLayout pnlIngresosEgresosProspectoLayout = new javax.swing.GroupLayout(pnlIngresosEgresosProspecto);
        pnlIngresosEgresosProspecto.setLayout(pnlIngresosEgresosProspectoLayout);
        pnlIngresosEgresosProspectoLayout.setHorizontalGroup(
            pnlIngresosEgresosProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosEgresosProspectoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlIngresosEgresosProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEgresosProspecto)
                    .addComponent(lblIngresosProspecto)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnlIngresosEgresosProspectoLayout.setVerticalGroup(
            pnlIngresosEgresosProspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosEgresosProspectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresosProspecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEgresosProspecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        tblpSolicitudCreditoProspecto.addTab("Ingresos y egresos", pnlIngresosEgresosProspecto);

        btnGuardarProspecto.setText("Guardar");

        javax.swing.GroupLayout pnlSolicitudCreditosLayout = new javax.swing.GroupLayout(pnlSolicitudCreditos);
        pnlSolicitudCreditos.setLayout(pnlSolicitudCreditosLayout);
        pnlSolicitudCreditosLayout.setHorizontalGroup(
            pnlSolicitudCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblpSolicitudCreditoProspecto)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudCreditosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarProspecto)
                .addGap(28, 28, 28))
        );
        pnlSolicitudCreditosLayout.setVerticalGroup(
            pnlSolicitudCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblpSolicitudCreditoProspecto, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnGuardarProspecto)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Solicitud de Creditos", pnlSolicitudCreditos);

        pnlSolicitanteAhorro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlSolicitanteAhorro.setToolTipText("");
        pnlSolicitanteAhorro.setName(""); // NOI18N

        lblNombreAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreAhorro.setText("Nombre:");
        lblNombreAhorro.setName("lblNombreAhorro"); // NOI18N

        txtNombreAhorro.setName("txtNombreAhorro"); // NOI18N

        lblDUIAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDUIAhorro.setText("DUI:");
        lblDUIAhorro.setName("lblDUIAhorro"); // NOI18N

        txtDUIAhorro.setName("txtDUIAhorro"); // NOI18N

        lblFechaNacAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaNacAhorro.setText("Fecha de apertura:");

        lblTelefonoAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefonoAhorro.setText("Termino:");
        lblTelefonoAhorro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblCuentaAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCuentaAhorro.setText("Cuenta:");

        lblTasaAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTasaAhorro.setText("Tasa de interes:");

        lblTipoDocumentoAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoDocumentoAhorro.setText("Tipo documento:");
        lblTipoDocumentoAhorro.setToolTipText("");

        cboTipoDocumentoAhorro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboTipoCuentaAhorro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipoCuentaAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoCuentaAhorro.setText("Tipo de Cuenta:");

        lblFechaNacAhorro1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaNacAhorro1.setText("Fecha de cancelación:");

        lblMontoAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMontoAhorro.setText("Monto:");

        lblBeneficiarioAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBeneficiarioAhorro.setText("Beneficiarios:");

        txaBeneficiarioAhorro.setColumns(20);
        txaBeneficiarioAhorro.setRows(5);
        scrBeneficiarioAhorro.setViewportView(txaBeneficiarioAhorro);

        btnGuardarAhorro.setText("Guardar");

        javax.swing.GroupLayout pnlSolicitanteAhorroLayout = new javax.swing.GroupLayout(pnlSolicitanteAhorro);
        pnlSolicitanteAhorro.setLayout(pnlSolicitanteAhorroLayout);
        pnlSolicitanteAhorroLayout.setHorizontalGroup(
            pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                        .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteAhorroLayout.createSequentialGroup()
                                            .addComponent(lblFechaNacAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dcFechaAperturaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                                .addComponent(lblDUIAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDUIAhorro))
                                            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                                .addComponent(lblNombreAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombreAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtTelefonoAhorro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                            .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblFechaNacAhorro1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblMontoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtMontoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dcFechaCancelacionAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                            .addComponent(lblTipoDocumentoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cboTipoDocumentoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                        .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblTipoCuentaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(lblCuentaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboTipoCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBeneficiarioAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTasaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(lblTelefonoAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtTasaAhorro))
                                    .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrBeneficiarioAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteAhorroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSolicitanteAhorroLayout.setVerticalGroup(
            pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitanteAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboTipoCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoCuentaAhorro)
                    .addComponent(txtNombreAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreAhorro))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDUIAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDUIAhorro)
                    .addComponent(lblCuentaAhorro)
                    .addComponent(txtCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblFechaNacAhorro)
                    .addComponent(lblFechaNacAhorro1)
                    .addComponent(dcFechaAperturaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaCancelacionAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTelefonoAhorro)
                    .addComponent(txtTelefonoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoAhorro)
                    .addComponent(txtMontoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTasaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTasaAhorro)
                    .addComponent(lblTipoDocumentoAhorro)
                    .addComponent(cboTipoDocumentoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBeneficiarioAhorro)
                    .addComponent(scrBeneficiarioAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(btnGuardarAhorro)
                .addContainerGap())
        );

        tblSolicitudAhorro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrSolicitudAhorro.setViewportView(tblSolicitudAhorro);

        pnlBusquedaAhorro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de búqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtBusquedaNombreAhorro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblBusquedaNombreAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBusquedaNombreAhorro.setText("Nombre/Otro:");

        btnBusquedaBuscarAhorro.setText("Buscar");

        lblBuscarPorAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBuscarPorAhorro.setText("Buscar por:");

        cboBuscarPorAhorro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblBuscarFechaInicioAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBuscarFechaInicioAhorro.setText("Fecha inicio:");

        jTextField2.setText("temporal");

        lblBuscarFechaFinAhorro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBuscarFechaFinAhorro.setText("Fecha fin:");

        jTextField3.setText("temporal");

        javax.swing.GroupLayout pnlBusquedaAhorroLayout = new javax.swing.GroupLayout(pnlBusquedaAhorro);
        pnlBusquedaAhorro.setLayout(pnlBusquedaAhorroLayout);
        pnlBusquedaAhorroLayout.setHorizontalGroup(
            pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBusquedaAhorroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBusquedaBuscarAhorro))
                    .addGroup(pnlBusquedaAhorroLayout.createSequentialGroup()
                        .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBusquedaNombreAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(lblBuscarPorAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBuscarFechaInicioAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboBuscarPorAhorro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBusquedaNombreAhorro)
                            .addGroup(pnlBusquedaAhorroLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBuscarFechaFinAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlBusquedaAhorroLayout.setVerticalGroup(
            pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPorAhorro)
                    .addComponent(cboBuscarPorAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaNombreAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusquedaNombreAhorro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBusquedaAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarFechaInicioAhorro)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarFechaFinAhorro)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnBusquedaBuscarAhorro))
        );

        lblNombrePantalla.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNombrePantalla.setText("Solicitud de ahorro");

        javax.swing.GroupLayout pnlSolicitudAhorroLayout = new javax.swing.GroupLayout(pnlSolicitudAhorro);
        pnlSolicitudAhorro.setLayout(pnlSolicitudAhorroLayout);
        pnlSolicitudAhorroLayout.setHorizontalGroup(
            pnlSolicitudAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitudAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombrePantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSolicitudAhorroLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrSolicitudAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlBusquedaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSolicitanteAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSolicitudAhorroLayout.setVerticalGroup(
            pnlSolicitudAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePantalla)
                .addGap(28, 28, 28)
                .addGroup(pnlSolicitudAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitudAhorroLayout.createSequentialGroup()
                        .addComponent(pnlBusquedaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrSolicitudAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pnlSolicitanteAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Solicitud de Ahorro", pnlSolicitudAhorro);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Solicitud de Deposito a Plazo", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Generacion de Reportes", jPanel6);

        jLabel3.setText("Espacio para una barra de estado");

        javax.swing.GroupLayout pnlBarraEstadoLayout = new javax.swing.GroupLayout(pnlBarraEstado);
        pnlBarraEstado.setLayout(pnlBarraEstadoLayout);
        pnlBarraEstadoLayout.setHorizontalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBarraEstadoLayout.setVerticalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Atencion al Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Creditos");
        jMenu1.add(jMenuItem3);

        Mora.setText("Mora");
        Mora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoraActionPerformed(evt);
            }
        });
        jMenu1.add(Mora);

        jMenuItem4.setText("Caja");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Ingresos y Egresos");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Contabilidad");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarraEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new atencionCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoraActionPerformed

    private void txtEmpresaProspectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaProspectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaProspectoActionPerformed

    private void txtTelefonoProspectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProspectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProspectoActionPerformed

    private void txtMontoReferenciaProspectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoReferenciaProspectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoReferenciaProspectoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mora;
    private javax.swing.JButton btnBusquedaBuscarAhorro;
    private javax.swing.JButton btnGuardarAhorro;
    private javax.swing.JButton btnGuardarProspecto;
    private javax.swing.JComboBox<String> cboBuscarPorAhorro;
    private javax.swing.JComboBox<String> cboTipoCuentaAhorro;
    private javax.swing.JComboBox<String> cboTipoDocumentoAhorro;
    private javax.swing.JCheckBox cbxEsEmpleadoProspecto;
    private javax.swing.JCheckBox cbxEsPencionadoProspecto;
    private com.toedter.calendar.JDateChooser dcFechaAperturaAhorro;
    private com.toedter.calendar.JDateChooser dcFechaCancelacionAhorro;
    private com.toedter.calendar.JDateChooser dcFechaNacimientoProspecto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblBeneficiarioAhorro;
    private javax.swing.JLabel lblBuscarFechaFinAhorro;
    private javax.swing.JLabel lblBuscarFechaInicioAhorro;
    private javax.swing.JLabel lblBuscarPorAhorro;
    private javax.swing.JLabel lblBusquedaNombreAhorro;
    private javax.swing.JLabel lblCargoProspecto;
    private javax.swing.JLabel lblCuentaAhorro;
    private javax.swing.JLabel lblDUIAhorro;
    private javax.swing.JLabel lblDireccionProspecto;
    private javax.swing.JLabel lblDuiProspecto;
    private javax.swing.JLabel lblEgresosProspecto;
    private javax.swing.JLabel lblEmpresaProspecto;
    private javax.swing.JLabel lblFechaNacAhorro;
    private javax.swing.JLabel lblFechaNacAhorro1;
    private javax.swing.JLabel lblFechaNacimientoProspecto;
    private javax.swing.JLabel lblFormaPagoProspecto;
    private javax.swing.JLabel lblGradoDiscapacidadProspecto;
    private javax.swing.JLabel lblIngresosProspecto;
    private javax.swing.JLabel lblMontoAhorro;
    private javax.swing.JLabel lblMontoPencionProspecto;
    private javax.swing.JLabel lblMontoReferenciaProspecto;
    private javax.swing.JLabel lblNombreAhorro;
    private javax.swing.JLabel lblNombrePantalla;
    private javax.swing.JLabel lblNombreProspecto;
    private javax.swing.JLabel lblPlazoMesesProspecto;
    private javax.swing.JLabel lblSalarioProspecto;
    private javax.swing.JLabel lblTasaAhorro;
    private javax.swing.JLabel lblTelefonoAhorro;
    private javax.swing.JLabel lblTelefonoProspecto;
    private javax.swing.JLabel lblTiempoLaboradoProspecto;
    private javax.swing.JLabel lblTipoCuentaAhorro;
    private javax.swing.JLabel lblTipoDocumentoAhorro;
    private javax.swing.JLabel lblTipoGarantiaProspecto;
    private javax.swing.JLabel lblTipoPrestamoProspecto;
    private javax.swing.JLabel lblmontoProspecto;
    private javax.swing.JPanel pnlBarraEstado;
    private javax.swing.JPanel pnlBusquedaAhorro;
    private javax.swing.JPanel pnlCriteriosBusquedaProspecto;
    private javax.swing.JPanel pnlGeneralProspecto;
    private javax.swing.JPanel pnlIngresosEgresosProspecto;
    private javax.swing.JPanel pnlReferenciaBancariasProspecto;
    private javax.swing.JPanel pnlReferenciaInternaProspecto;
    private javax.swing.JPanel pnlReferenciasPersonalesProspecto;
    private javax.swing.JPanel pnlReferenciasProspecto;
    private javax.swing.JPanel pnlSolicitanteAhorro;
    private javax.swing.JPanel pnlSolicitantesProspecto;
    private javax.swing.JPanel pnlSolicitudAhorro;
    private javax.swing.JPanel pnlSolicitudCreditos;
    private javax.swing.JScrollPane scrBeneficiarioAhorro;
    private javax.swing.JScrollPane scrSolicitudAhorro;
    private javax.swing.JTable tblEgresosProspectos;
    private javax.swing.JTable tblIngresosProspecto;
    private javax.swing.JTable tblReferenciasBancariasProspecto;
    private javax.swing.JTable tblReferenciasPersonalesProspecto;
    private javax.swing.JTable tblSolicitudAhorro;
    private javax.swing.JTabbedPane tblpSolicitudCreditoProspecto;
    private javax.swing.JTextArea txaBeneficiarioAhorro;
    private javax.swing.JTextArea txaDireccionProspecto;
    private javax.swing.JTextField txtBusquedaNombreAhorro;
    private javax.swing.JTextField txtCargoProspecto;
    private javax.swing.JTextField txtCuentaAhorro;
    private javax.swing.JTextField txtDUIAhorro;
    private javax.swing.JTextField txtDuiSolicitanteProspecto;
    private javax.swing.JTextField txtEmpresaProspecto;
    private javax.swing.JTextField txtFormaPagoProspecto;
    private javax.swing.JTextField txtGradoDiscapacidadProspecto;
    private javax.swing.JTextField txtMontoAhorro;
    private javax.swing.JTextField txtMontoPensionProspecto;
    private javax.swing.JTextField txtMontoProspecto;
    private javax.swing.JTextField txtMontoReferenciaProspecto;
    private javax.swing.JTextField txtNombreAhorro;
    private javax.swing.JTextField txtNombreSolicitanteProspecto;
    private javax.swing.JTextField txtPlazoMesesPropuesta;
    private javax.swing.JTextField txtSalarioProspecto;
    private javax.swing.JTextField txtTasaAhorro;
    private javax.swing.JTextField txtTelefonoAhorro;
    private javax.swing.JTextField txtTelefonoProspecto;
    private javax.swing.JTextField txtTiempoLaboradoProspecto;
    private javax.swing.JTextField txtTipoGarantiaProspecto;
    private javax.swing.JTextField txtTipoPrestamoProspecto;
    // End of variables declaration//GEN-END:variables
}
