package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;


/**
 * Citas generated by hbm2java
 */
@Entity
@Table(name="citas"
    ,catalog="sirac_bd"
)
public class Citas  implements java.io.Serializable {


     private int idcitas;
     private Paciente paciente;
     private Usuario usuario;
     private String descripcioncita;
     private Date fechacita;
     private String nombredoctorcita;
     private String tipocita;
     private String estadocita;
    

    public Citas() {
    }

	
    public Citas(int idcitas) {
        this.idcitas = idcitas;
    }
    public Citas(int idcitas, Paciente paciente, Usuario usuario, String descripcioncita, Date fechacita, String nombredoctorcita, String tipocita, String estadocita) {
       this.idcitas = idcitas;
       this.paciente = paciente;
       this.usuario = usuario;
       this.descripcioncita = descripcioncita;
       this.fechacita = fechacita;
       this.nombredoctorcita = nombredoctorcita;
       this.tipocita = tipocita;
       this.estadocita = estadocita;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="IDCITAS", unique=true, nullable=false)
    public int getIdcitas() {
        return this.idcitas;
    }
    
    public void setIdcitas(int idcitas) {
        this.idcitas = idcitas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPACIENTE")
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIO")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="DESCRIPCIONCITA", length=200)
    public String getDescripcioncita() {
        return this.descripcioncita;
    }
    
    public void setDescripcioncita(String descripcioncita) {
        this.descripcioncita = descripcioncita;
    }

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern="dd-mm-yyyy")
    @Column(name="FECHACITA", length=10)
    public Date getFechacita() {
        return this.fechacita;
    }
    
    public void setFechacita(Date fechacita) {
        this.fechacita = fechacita;
    }

    
    @Column(name="NOMBREDOCTORCITA", length=50)
    public String getNombredoctorcita() {
        return this.nombredoctorcita;
    }
    
    public void setNombredoctorcita(String nombredoctorcita) {
        this.nombredoctorcita = nombredoctorcita;
    }

    
    @Column(name="TIPOCITA", length=15)
    public String getTipocita() {
        return this.tipocita;
    }
    
    public void setTipocita(String tipocita) {
        this.tipocita = tipocita;
    }

    
    @Column(name="ESTADOCITA", length=15)
    public String getEstadocita() {
        return this.estadocita;
    }
    
    public void setEstadocita(String estadocita) {
        this.estadocita = estadocita;
    }
}


