package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contaco generated by hbm2java
 */
@Entity
@Table(name="contaco"
    ,catalog="sirac_bd"
)
public class Contaco  implements java.io.Serializable {


     private int idcontacto;
     private String nombrecontacto;
     private String apellidocontacto;
     private String empresacontacto;
     private String titulocontacto;
     private String direccioncontacto;
     private String ciudadcontacto;
    

    public Contaco() {
    }

	
    public Contaco(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public Contaco(int idcontacto, String nombrecontacto, String apellidocontacto, String empresacontacto, String titulocontacto, String direccioncontacto, String ciudadcontacto, Set telefonos) {
       this.idcontacto = idcontacto;
       this.nombrecontacto = nombrecontacto;
       this.apellidocontacto = apellidocontacto;
       this.empresacontacto = empresacontacto;
       this.titulocontacto = titulocontacto;
       this.direccioncontacto = direccioncontacto;
       this.ciudadcontacto = ciudadcontacto;
       
    }
   
     @Id 
    @Column(name="IDCONTACTO", unique=true, nullable=false)
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }

    
    @Column(name="NOMBRECONTACTO", length=50)
    public String getNombrecontacto() {
        return this.nombrecontacto;
    }
    
    public void setNombrecontacto(String nombrecontacto) {
        this.nombrecontacto = nombrecontacto;
    }

    
    @Column(name="APELLIDOCONTACTO", length=50)
    public String getApellidocontacto() {
        return this.apellidocontacto;
    }
    
    public void setApellidocontacto(String apellidocontacto) {
        this.apellidocontacto = apellidocontacto;
    }

    
    @Column(name="EMPRESACONTACTO", length=50)
    public String getEmpresacontacto() {
        return this.empresacontacto;
    }
    
    public void setEmpresacontacto(String empresacontacto) {
        this.empresacontacto = empresacontacto;
    }

    
    @Column(name="TITULOCONTACTO", length=15)
    public String getTitulocontacto() {
        return this.titulocontacto;
    }
    
    public void setTitulocontacto(String titulocontacto) {
        this.titulocontacto = titulocontacto;
    }

    
    @Column(name="DIRECCIONCONTACTO", length=100)
    public String getDireccioncontacto() {
        return this.direccioncontacto;
    }
    
    public void setDireccioncontacto(String direccioncontacto) {
        this.direccioncontacto = direccioncontacto;
    }

    
    @Column(name="CIUDADCONTACTO", length=15)
    public String getCiudadcontacto() {
        return this.ciudadcontacto;
    }
    
    public void setCiudadcontacto(String ciudadcontacto) {
        this.ciudadcontacto = ciudadcontacto;
    }






}


