package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="sirac_bd"
)
public class Paciente  implements java.io.Serializable {


     private int idpaciente;
     private String nombrepaciente;
     private String apellidopaciente;
     private String seguropaciente;
     private Date fechanacimientopaciente;
     private String lugatrabajopaciente;
     private String profesionpaciente;
     private Float saldopaciente;
     private Boolean morapaciente;
     private byte[] fotopefilpaciente;
    

    public Paciente() {
    }

	
    public Paciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }
    public Paciente(int idpaciente, String nombrepaciente, String apellidopaciente, String seguropaciente, Date fechanacimientopaciente, String lugatrabajopaciente, String profesionpaciente, Float saldopaciente, Boolean morapaciente, byte[] fotopefilpaciente, Set telefonos, Set citases) {
       this.idpaciente = idpaciente;
       this.nombrepaciente = nombrepaciente;
       this.apellidopaciente = apellidopaciente;
       this.seguropaciente = seguropaciente;
       this.fechanacimientopaciente = fechanacimientopaciente;
       this.lugatrabajopaciente = lugatrabajopaciente;
       this.profesionpaciente = profesionpaciente;
       this.saldopaciente = saldopaciente;
       this.morapaciente = morapaciente;
       this.fotopefilpaciente = fotopefilpaciente;
      
    }
   
     @Id 

    
    @Column(name="IDPACIENTE", unique=true, nullable=false)
    public int getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }

    
    @Column(name="NOMBREPACIENTE", length=50)
    public String getNombrepaciente() {
        return this.nombrepaciente;
    }
    
    public void setNombrepaciente(String nombrepaciente) {
        this.nombrepaciente = nombrepaciente;
    }

    
    @Column(name="APELLIDOPACIENTE", length=50)
    public String getApellidopaciente() {
        return this.apellidopaciente;
    }
    
    public void setApellidopaciente(String apellidopaciente) {
        this.apellidopaciente = apellidopaciente;
    }

    
    @Column(name="SEGUROPACIENTE", length=50)
    public String getSeguropaciente() {
        return this.seguropaciente;
    }
    
    public void setSeguropaciente(String seguropaciente) {
        this.seguropaciente = seguropaciente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHANACIMIENTOPACIENTE", length=10)
    public Date getFechanacimientopaciente() {
        return this.fechanacimientopaciente;
    }
    
    public void setFechanacimientopaciente(Date fechanacimientopaciente) {
        this.fechanacimientopaciente = fechanacimientopaciente;
    }

    
    @Column(name="LUGATRABAJOPACIENTE", length=50)
    public String getLugatrabajopaciente() {
        return this.lugatrabajopaciente;
    }
    
    public void setLugatrabajopaciente(String lugatrabajopaciente) {
        this.lugatrabajopaciente = lugatrabajopaciente;
    }

    
    @Column(name="PROFESIONPACIENTE", length=25)
    public String getProfesionpaciente() {
        return this.profesionpaciente;
    }
    
    public void setProfesionpaciente(String profesionpaciente) {
        this.profesionpaciente = profesionpaciente;
    }

    
    @Column(name="SALDOPACIENTE", precision=8)
    public Float getSaldopaciente() {
        return this.saldopaciente;
    }
    
    public void setSaldopaciente(Float saldopaciente) {
        this.saldopaciente = saldopaciente;
    }

    
    @Column(name="MORAPACIENTE")
    public Boolean getMorapaciente() {
        return this.morapaciente;
    }
    
    public void setMorapaciente(Boolean morapaciente) {
        this.morapaciente = morapaciente;
    }

    
    @Column(name="FOTOPEFILPACIENTE")
    public byte[] getFotopefilpaciente() {
        return this.fotopefilpaciente;
    }
    
    public void setFotopefilpaciente(byte[] fotopefilpaciente) {
        this.fotopefilpaciente = fotopefilpaciente;
    }





}


