package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name="receta"
    ,catalog="sirac_bd"
)
public class Receta  implements java.io.Serializable {


     private int idreceta;
     private Citas citas;
     private String descripcionreceta;

    public Receta() {
    }

	
    public Receta(int idreceta) {
        this.idreceta = idreceta;
    }
    public Receta(int idreceta, Citas citas, String descripcionreceta) {
       this.idreceta = idreceta;
       this.citas = citas;
       this.descripcionreceta = descripcionreceta;
    }
   
     @Id 

    
    @Column(name="IDRECETA", unique=true, nullable=false)
    public int getIdreceta() {
        return this.idreceta;
    }
    
    public void setIdreceta(int idreceta) {
        this.idreceta = idreceta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCITAS")
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }

    
    @Column(name="DESCRIPCIONRECETA", length=200)
    public String getDescripcionreceta() {
        return this.descripcionreceta;
    }
    
    public void setDescripcionreceta(String descripcionreceta) {
        this.descripcionreceta = descripcionreceta;
    }




}


