package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;


/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="sirac_bd"
)
public class Telefono  implements java.io.Serializable {


     private int idtelefono;
     private Contaco contaco;
     private Paciente paciente;
     private String numerotelefono;
     private String tipotelefono;

    public Telefono() {
    }

	
    public Telefono(int idtelefono) {
        this.idtelefono = idtelefono;
    }
    public Telefono(int idtelefono, Contaco contaco, Paciente paciente, String numerotelefono, String tipotelefono) {
       this.idtelefono = idtelefono;
       this.contaco = contaco;
       this.paciente = paciente;
       this.numerotelefono = numerotelefono;
       this.tipotelefono = tipotelefono;
    }
   
     @Id 
    @Column(name="IDTELEFONO", unique=true, nullable=false)
    public int getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(int idtelefono) {
        this.idtelefono = idtelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTACTO")
    public Contaco getContaco() {
        return this.contaco;
    }
    
    public void setContaco(Contaco contaco) {
        this.contaco = contaco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPACIENTE")
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="NUMEROTELEFONO", length=9)
    public String getNumerotelefono() {
        return this.numerotelefono;
    }
    
    public void setNumerotelefono(String numerotelefono) {
        this.numerotelefono = numerotelefono;
    }

    
    @Column(name="TIPOTELEFONO", length=9)
    public String getTipotelefono() {
        return this.tipotelefono;
    }
    
    public void setTipotelefono(String tipotelefono) {
        this.tipotelefono = tipotelefono;
    }




}


