package net.cuscatlan.clinica.model;
// Generated 12-12-2017 11:03:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="sirac_bd"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String correousuario;
     private String claveusuario;
   

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String nombreusuario, String correousuario, String claveusuario) {
       this.idusuario = idusuario;
       this.nombreusuario = nombreusuario;
       this.correousuario = correousuario;
       this.claveusuario = claveusuario;
    
    }
   
     @Id 

    
    @Column(name="IDUSUARIO", unique=true, nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="NOMBREUSUARIO", length=100)
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    
    @Column(name="CORREOUSUARIO", length=50)
    public String getCorreousuario() {
        return this.correousuario;
    }
    
    public void setCorreousuario(String correousuario) {
        this.correousuario = correousuario;
    }

    
    @Column(name="CLAVEUSUARIO", length=15)
    public String getClaveusuario() {
        return this.claveusuario;
    }
    
    public void setClaveusuario(String claveusuario) {
        this.claveusuario = claveusuario;
    }





}


