package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dboalmacen generated by hbm2java
 */
public class Dboalmacen  implements java.io.Serializable {


     private String codigo;
     private String sucursal;
     private String nombre;
     private String codigoFac;

    public Dboalmacen() {
    }

    public Dboalmacen(String codigo, String sucursal, String nombre, String codigoFac) {
       this.codigo = codigo;
       this.sucursal = sucursal;
       this.nombre = nombre;
       this.codigoFac = codigoFac;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigoFac() {
        return this.codigoFac;
    }
    
    public void setCodigoFac(String codigoFac) {
        this.codigoFac = codigoFac;
    }




}


