package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dbobeneficiarios generated by hbm2java
 */
public class Dbobeneficiarios  implements java.io.Serializable {


     private Integer id;
     private String codigoCliente;
     private String nombre;
     private String dui;
     private String nit;
     private String telefono;
     private String direccion;
     private Integer departamento;
     private Integer municipio;
     private String canton;
     private Date fechaNacimiento;
     private Integer sexo;
     private String parantesco;
     private String tutorNombre;
     private Integer porcentaje;

    public Dbobeneficiarios() {
    }

    public Dbobeneficiarios(String codigoCliente, String nombre, String dui, String nit, String telefono, String direccion, Integer departamento, Integer municipio, String canton, Date fechaNacimiento, Integer sexo, String parantesco, String tutorNombre, Integer porcentaje) {
       this.codigoCliente = codigoCliente;
       this.nombre = nombre;
       this.dui = dui;
       this.nit = nit;
       this.telefono = telefono;
       this.direccion = direccion;
       this.departamento = departamento;
       this.municipio = municipio;
       this.canton = canton;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.parantesco = parantesco;
       this.tutorNombre = tutorNombre;
       this.porcentaje = porcentaje;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(String codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Integer departamento) {
        this.departamento = departamento;
    }
    public Integer getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Integer municipio) {
        this.municipio = municipio;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }
    public String getParantesco() {
        return this.parantesco;
    }
    
    public void setParantesco(String parantesco) {
        this.parantesco = parantesco;
    }
    public String getTutorNombre() {
        return this.tutorNombre;
    }
    
    public void setTutorNombre(String tutorNombre) {
        this.tutorNombre = tutorNombre;
    }
    public Integer getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Integer porcentaje) {
        this.porcentaje = porcentaje;
    }




}


