package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dboclientes generated by hbm2java
 */
public class Dboclientes  implements java.io.Serializable {


     private String id;
     private String fechaIngreso;
     private String numDui;
     private String nit;
     private String nombrecliente;
     private String apaterno;
     private String amaterno;
     private String pnombre;
     private String snombre;
     private String fechaNacio;
     private String sexo;
     private String departamento;
     private String municipio;
     private String direccion;
     private String duiProfesion;
     private String estadoCivil;
     private String telefono1;
     private String telefono2;
     private String cargo;
     private String estadoCliente;
     private String empleado;
     private String canton;
     private String duiDireccion;

    public Dboclientes() {
    }

	
    public Dboclientes(String id, String nombrecliente) {
        this.id = id;
        this.nombrecliente = nombrecliente;
    }
    public Dboclientes(String id, String fechaIngreso, String numDui, String nit, String nombrecliente, String apaterno, String amaterno, String pnombre, String snombre, String fechaNacio, String sexo, String departamento, String municipio, String direccion, String duiProfesion, String estadoCivil, String telefono1, String telefono2, String cargo, String estadoCliente, String empleado, String canton, String duiDireccion) {
       this.id = id;
       this.fechaIngreso = fechaIngreso;
       this.numDui = numDui;
       this.nit = nit;
       this.nombrecliente = nombrecliente;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.pnombre = pnombre;
       this.snombre = snombre;
       this.fechaNacio = fechaNacio;
       this.sexo = sexo;
       this.departamento = departamento;
       this.municipio = municipio;
       this.direccion = direccion;
       this.duiProfesion = duiProfesion;
       this.estadoCivil = estadoCivil;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.cargo = cargo;
       this.estadoCliente = estadoCliente;
       this.empleado = empleado;
       this.canton = canton;
       this.duiDireccion = duiDireccion;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getNumDui() {
        return this.numDui;
    }
    
    public void setNumDui(String numDui) {
        this.numDui = numDui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombrecliente() {
        return this.nombrecliente;
    }
    
    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }
    public String getFechaNacio() {
        return this.fechaNacio;
    }
    
    public void setFechaNacio(String fechaNacio) {
        this.fechaNacio = fechaNacio;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDuiProfesion() {
        return this.duiProfesion;
    }
    
    public void setDuiProfesion(String duiProfesion) {
        this.duiProfesion = duiProfesion;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getEstadoCliente() {
        return this.estadoCliente;
    }
    
    public void setEstadoCliente(String estadoCliente) {
        this.estadoCliente = estadoCliente;
    }
    public String getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(String empleado) {
        this.empleado = empleado;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getDuiDireccion() {
        return this.duiDireccion;
    }
    
    public void setDuiDireccion(String duiDireccion) {
        this.duiDireccion = duiDireccion;
    }




}


