package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbocategoria generated by hbm2java
 */
public class Dbocategoria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;

    public Dbocategoria() {
    }

    public Dbocategoria(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


