package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dbocliente generated by hbm2java
 */
public class Dbocliente  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int cliente;
     private String nit;
     private String dui;
     private String direccion;
     private String telefono;
     private String celular;
     private int estado;
     private Date fecha;

    public Dbocliente() {
    }

	
    public Dbocliente(String nombre, int cliente, int estado, Date fecha) {
        this.nombre = nombre;
        this.cliente = cliente;
        this.estado = estado;
        this.fecha = fecha;
    }
    public Dbocliente(String nombre, int cliente, String nit, String dui, String direccion, String telefono, String celular, int estado, Date fecha) {
       this.nombre = nombre;
       this.cliente = cliente;
       this.nit = nit;
       this.dui = dui;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.estado = estado;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCliente() {
        return this.cliente;
    }
    
    public void setCliente(int cliente) {
        this.cliente = cliente;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


