package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Dbocaja generated by hbm2java
 */
public class Dbocaja  implements java.io.Serializable {


     private Integer idregcaja;
     private BigDecimal montoingre;
     private String idcajero;
     private String fechaingre;
     private String iduseringre;
     private BigDecimal montocierre;

    public Dbocaja() {
    }

    public Dbocaja(BigDecimal montoingre, String idcajero, String fechaingre, String iduseringre, BigDecimal montocierre) {
       this.montoingre = montoingre;
       this.idcajero = idcajero;
       this.fechaingre = fechaingre;
       this.iduseringre = iduseringre;
       this.montocierre = montocierre;
    }
   
    public Integer getIdregcaja() {
        return this.idregcaja;
    }
    
    public void setIdregcaja(Integer idregcaja) {
        this.idregcaja = idregcaja;
    }
    public BigDecimal getMontoingre() {
        return this.montoingre;
    }
    
    public void setMontoingre(BigDecimal montoingre) {
        this.montoingre = montoingre;
    }
    public String getIdcajero() {
        return this.idcajero;
    }
    
    public void setIdcajero(String idcajero) {
        this.idcajero = idcajero;
    }
    public String getFechaingre() {
        return this.fechaingre;
    }
    
    public void setFechaingre(String fechaingre) {
        this.fechaingre = fechaingre;
    }
    public String getIduseringre() {
        return this.iduseringre;
    }
    
    public void setIduseringre(String iduseringre) {
        this.iduseringre = iduseringre;
    }
    public BigDecimal getMontocierre() {
        return this.montocierre;
    }
    
    public void setMontocierre(BigDecimal montocierre) {
        this.montocierre = montocierre;
    }




}


