package com.avrilco.Entidades;
// Generated 12-11-2017 10:02:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dboclientes generated by hbm2java
 */
@Entity
@Table(name = "Dboclientes",
         catalog = "siscooperativa"
)
public class Dboclientes implements java.io.Serializable {

    private String id;
    private String amaterno;
    private String apaterno;
    private String canton;
    private String cargo;
    private String departamento;
    private String direccion;
    private String dui_direccion;
    private String dui_profesion;
    private String empleado;
    private String estado_civil;
    private String estado_cliente;
    private String fecha_ingreso;
    private String fecha_nacio;
    private String municipio;
    private String nit;
    private String nombrecliente;
    private String num_dui;
    private String pnombre;
    private String sexo;
    private String snombre;
    private String telefono1;
    private String telefono2;

    public Dboclientes() {
    }

    public Dboclientes(String id) {
        this.id = id;
    }

    public Dboclientes(String id, String amaterno, String apaterno, String canton, String cargo, String departamento, String direccion, String dui_direccion, String dui_profesion, String empleado, String estado_civil, String estado_cliente, String fecha_ingreso, String fecha_nacio, String municipio, String nit, String nombrecliente, String num_dui, String pnombre, String sexo, String snombre, String telefono1, String telefono2) {
        this.id = id;
        this.amaterno = amaterno;
        this.apaterno = apaterno;
        this.canton = canton;
        this.cargo = cargo;
        this.departamento = departamento;
        this.direccion = direccion;
        this.dui_direccion = dui_direccion;
        this.dui_profesion = dui_profesion;
        this.empleado = empleado;
        this.estado_civil = estado_civil;
        this.estado_cliente = estado_cliente;
        this.fecha_ingreso = fecha_ingreso;
        this.fecha_nacio = fecha_nacio;
        this.municipio = municipio;
        this.nit = nit;
        this.nombrecliente = nombrecliente;
        this.num_dui = num_dui;
        this.pnombre = pnombre;
        this.sexo = sexo;
        this.snombre = snombre;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
    }

    @Id
    @Column(name = "id", nullable = false)
  //@GeneratedValue(strategy = GenerationType.IDENTITY)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "amaterno")
    public String getAmaterno() {
        return this.amaterno;
    }

    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    @Column(name = "apaterno")
    public String getApaterno() {
        return this.apaterno;
    }

    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    @Column(name = "canton")
    public String getCanton() {
        return this.canton;
    }

    public void setCanton(String canton) {
        this.canton = canton;
    }

    @Column(name = "cargo")
    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    @Column(name = "departamento")
    public String getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Column(name = "direccion")
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "dui_direccion")
    public String getDui_direccion() {
        return this.dui_direccion;
    }

    public void setDui_direccion(String dui_direccion) {
        this.dui_direccion = dui_direccion;
    }

    @Column(name = "dui_profesion")
    public String getDui_profesion() {
        return this.dui_profesion;
    }

    public void setDui_profesion(String dui_profesion) {
        this.dui_profesion = dui_profesion;
    }

    @Column(name = "empleado")
    public String getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(String empleado) {
        this.empleado = empleado;
    }

    @Column(name = "estado_civil")
    public String getEstado_civil() {
        return this.estado_civil;
    }

    public void setEstado_civil(String estado_civil) {
        this.estado_civil = estado_civil;
    }

    @Column(name = "estado_cliente")
    public String getEstado_cliente() {
        return this.estado_cliente;
    }

    public void setEstado_cliente(String estado_cliente) {
        this.estado_cliente = estado_cliente;
    }

    @Column(name = "fecha_ingreso")
    public String getFecha_ingreso() {
        return this.fecha_ingreso;
    }

    public void setFecha_ingreso(String fecha_ingreso) {
        this.fecha_ingreso = fecha_ingreso;
    }

    @Column(name = "fecha_nacio")
    public String getFecha_nacio() {
        return this.fecha_nacio;
    }

    public void setFecha_nacio(String fecha_nacio) {
        this.fecha_nacio = fecha_nacio;
    }

    @Column(name = "municipio")
    public String getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    @Column(name = "nit")
    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    @Column(name = "nombrecliente")
    public String getNombrecliente() {
        return this.nombrecliente;
    }

    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }

    @Column(name = "num_dui")
    public String getNum_dui() {
        return this.num_dui;
    }

    public void setNum_dui(String num_dui) {
        this.num_dui = num_dui;
    }

    @Column(name = "pnombre")
    public String getPnombre() {
        return this.pnombre;
    }

    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }

    @Column(name = "sexo")
    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Column(name = "snombre")
    public String getSnombre() {
        return this.snombre;
    }

    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }

    @Column(name = "telefono1")
    public String getTelefono1() {
        return this.telefono1;
    }

    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }

    @Column(name = "telefono2")
    public String getTelefono2() {
        return this.telefono2;
    }

    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

}
