package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Dbodetalletransaccion generated by hbm2java
 */
public class Dbodetalletransaccion  implements java.io.Serializable {


     private Integer id;
     private String producto;
     private int cantidad;
     private int unidad;
     private BigDecimal precioUnitario;
     private double descuento;
     private int orden;
     private int tipoPago;
     private String categoria;
     private int tipoRango;

    public Dbodetalletransaccion() {
    }

    public Dbodetalletransaccion(String producto, int cantidad, int unidad, BigDecimal precioUnitario, double descuento, int orden, int tipoPago, String categoria, int tipoRango) {
       this.producto = producto;
       this.cantidad = cantidad;
       this.unidad = unidad;
       this.precioUnitario = precioUnitario;
       this.descuento = descuento;
       this.orden = orden;
       this.tipoPago = tipoPago;
       this.categoria = categoria;
       this.tipoRango = tipoRango;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(int unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public int getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(int tipoPago) {
        this.tipoPago = tipoPago;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public int getTipoRango() {
        return this.tipoRango;
    }
    
    public void setTipoRango(int tipoRango) {
        this.tipoRango = tipoRango;
    }




}


