package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Dbodetalleordencompra generated by hbm2java
 */
public class Dbodetalleordencompra  implements java.io.Serializable {


     private Integer id;
     private int orden;
     private String codigoProducto;
     private int cantidad;
     private BigDecimal precioUnitario;

    public Dbodetalleordencompra() {
    }

    public Dbodetalleordencompra(int orden, String codigoProducto, int cantidad, BigDecimal precioUnitario) {
       this.orden = orden;
       this.codigoProducto = codigoProducto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }




}


