package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbodepartamentos generated by hbm2java
 */
public class Dbodepartamentos  implements java.io.Serializable {


     private int id;
     private String nombre;

    public Dbodepartamentos() {
    }

    public Dbodepartamentos(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


