package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbodepartamento generated by hbm2java
 */
public class Dbodepartamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String sucursal;

    public Dbodepartamento() {
    }

    public Dbodepartamento(String nombre, String sucursal) {
       this.nombre = nombre;
       this.sucursal = sucursal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }




}


