package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dboempleado generated by hbm2java
 */
public class Dboempleado  implements java.io.Serializable {


     private String dui;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String celular;
     private Date fechaNacimiento;
     private int estadoCivil;
     private Integer afiliadora;
     private String afp;
     private String isss;
     private String nit;
     private int cargo;
     private BigDecimal sueldo;
     private Date fechaIngreso;
     private int estado;
     private int sexo;
     private String sucursal;
     private int departamento;

    public Dboempleado() {
    }

	
    public Dboempleado(String dui, String nombre, String apellido, String direccion, String telefono, Date fechaNacimiento, int estadoCivil, int cargo, BigDecimal sueldo, Date fechaIngreso, int estado, int sexo, String sucursal, int departamento) {
        this.dui = dui;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
        this.cargo = cargo;
        this.sueldo = sueldo;
        this.fechaIngreso = fechaIngreso;
        this.estado = estado;
        this.sexo = sexo;
        this.sucursal = sucursal;
        this.departamento = departamento;
    }
    public Dboempleado(String dui, String nombre, String apellido, String direccion, String telefono, String celular, Date fechaNacimiento, int estadoCivil, Integer afiliadora, String afp, String isss, String nit, int cargo, BigDecimal sueldo, Date fechaIngreso, int estado, int sexo, String sucursal, int departamento) {
       this.dui = dui;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.fechaNacimiento = fechaNacimiento;
       this.estadoCivil = estadoCivil;
       this.afiliadora = afiliadora;
       this.afp = afp;
       this.isss = isss;
       this.nit = nit;
       this.cargo = cargo;
       this.sueldo = sueldo;
       this.fechaIngreso = fechaIngreso;
       this.estado = estado;
       this.sexo = sexo;
       this.sucursal = sucursal;
       this.departamento = departamento;
    }
   
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(int estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Integer getAfiliadora() {
        return this.afiliadora;
    }
    
    public void setAfiliadora(Integer afiliadora) {
        this.afiliadora = afiliadora;
    }
    public String getAfp() {
        return this.afp;
    }
    
    public void setAfp(String afp) {
        this.afp = afp;
    }
    public String getIsss() {
        return this.isss;
    }
    
    public void setIsss(String isss) {
        this.isss = isss;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public int getCargo() {
        return this.cargo;
    }
    
    public void setCargo(int cargo) {
        this.cargo = cargo;
    }
    public BigDecimal getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(BigDecimal sueldo) {
        this.sueldo = sueldo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public int getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(int departamento) {
        this.departamento = departamento;
    }




}


