package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dbogeneral generated by hbm2java
 */
public class Dbogeneral  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String giro;
     private String nrc;
     private String nit;
     private String telefono;
     private String direccion;
     private Date fecha;
     private String fondo;
     private Date activo;
     private BigDecimal impuesto;

    public Dbogeneral() {
    }

    public Dbogeneral(String nombre, String giro, String nrc, String nit, String telefono, String direccion, Date fecha, String fondo, Date activo, BigDecimal impuesto) {
       this.nombre = nombre;
       this.giro = giro;
       this.nrc = nrc;
       this.nit = nit;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fecha = fecha;
       this.fondo = fondo;
       this.activo = activo;
       this.impuesto = impuesto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public String getNrc() {
        return this.nrc;
    }
    
    public void setNrc(String nrc) {
        this.nrc = nrc;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFondo() {
        return this.fondo;
    }
    
    public void setFondo(String fondo) {
        this.fondo = fondo;
    }
    public Date getActivo() {
        return this.activo;
    }
    
    public void setActivo(Date activo) {
        this.activo = activo;
    }
    public BigDecimal getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(BigDecimal impuesto) {
        this.impuesto = impuesto;
    }




}


