package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dbolote generated by hbm2java
 */
public class Dbolote  implements java.io.Serializable {


     private Byte id;
     private String nunFac;
     private Date fecha;
     private String activa;
     private String sucursal;
     private int documento;

    public Dbolote() {
    }

    public Dbolote(String nunFac, Date fecha, String activa, String sucursal, int documento) {
       this.nunFac = nunFac;
       this.fecha = fecha;
       this.activa = activa;
       this.sucursal = sucursal;
       this.documento = documento;
    }
   
    public Byte getId() {
        return this.id;
    }
    
    public void setId(Byte id) {
        this.id = id;
    }
    public String getNunFac() {
        return this.nunFac;
    }
    
    public void setNunFac(String nunFac) {
        this.nunFac = nunFac;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getActiva() {
        return this.activa;
    }
    
    public void setActiva(String activa) {
        this.activa = activa;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public int getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(int documento) {
        this.documento = documento;
    }




}


