package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dbomovimiento generated by hbm2java
 */
public class Dbomovimiento  implements java.io.Serializable {


     private Integer id;
     private String producto;
     private int cantidad;
     private Date fecha;
     private String tipo;
     private String detalle;
     private String sucursal;
     private String almacen;
     private BigDecimal precio;

    public Dbomovimiento() {
    }

    public Dbomovimiento(String producto, int cantidad, Date fecha, String tipo, String detalle, String sucursal, String almacen, BigDecimal precio) {
       this.producto = producto;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.tipo = tipo;
       this.detalle = detalle;
       this.sucursal = sucursal;
       this.almacen = almacen;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public String getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(String almacen) {
        this.almacen = almacen;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


