package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbomonedad generated by hbm2java
 */
public class Dbomonedad  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String simbolo;

    public Dbomonedad() {
    }

    public Dbomonedad(String nombre, String simbolo) {
       this.nombre = nombre;
       this.simbolo = simbolo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }




}


