package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbomunicipios generated by hbm2java
 */
public class Dbomunicipios  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int departamento;

    public Dbomunicipios() {
    }

    public Dbomunicipios(int id, String nombre, int departamento) {
       this.id = id;
       this.nombre = nombre;
       this.departamento = departamento;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(int departamento) {
        this.departamento = departamento;
    }




}


