package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dboproveedor generated by hbm2java
 */
public class Dboproveedor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String ruc;
     private String direccion;
     private String telefono;
     private String fax;
     private String contacto;
     private String correo;
     private int estado;
     private String descripcion;
     private Date fecha;
     private String nit;

    public Dboproveedor() {
    }

	
    public Dboproveedor(String nombre, String ruc, String direccion, String telefono, int estado, Date fecha, String nit) {
        this.nombre = nombre;
        this.ruc = ruc;
        this.direccion = direccion;
        this.telefono = telefono;
        this.estado = estado;
        this.fecha = fecha;
        this.nit = nit;
    }
    public Dboproveedor(String nombre, String ruc, String direccion, String telefono, String fax, String contacto, String correo, int estado, String descripcion, Date fecha, String nit) {
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fax = fax;
       this.contacto = contacto;
       this.correo = correo;
       this.estado = estado;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.nit = nit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }




}


