package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dboproducto generated by hbm2java
 */
public class Dboproducto  implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String codigoSucursal;
     private String codigoAlmacen;
     private String nombre;
     private int cantidad;
     private int stock;
     private int categoria;
     private int unidad;
     private int monedad;
     private int procedencia;
     private BigDecimal precioCosto;
     private BigDecimal precioVenta;
     private double descuento;
     private String estado;
     private Date fecha;
     private String descripcion;
     private BigDecimal final_;
     private int proveedor;
     private int estante;

    public Dboproducto() {
    }

	
    public Dboproducto(String codigo, String codigoSucursal, String codigoAlmacen, String nombre, int cantidad, int stock, int categoria, int unidad, int monedad, int procedencia, BigDecimal precioCosto, BigDecimal precioVenta, double descuento, String estado, Date fecha, BigDecimal final_, int proveedor, int estante) {
        this.codigo = codigo;
        this.codigoSucursal = codigoSucursal;
        this.codigoAlmacen = codigoAlmacen;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.stock = stock;
        this.categoria = categoria;
        this.unidad = unidad;
        this.monedad = monedad;
        this.procedencia = procedencia;
        this.precioCosto = precioCosto;
        this.precioVenta = precioVenta;
        this.descuento = descuento;
        this.estado = estado;
        this.fecha = fecha;
        this.final_ = final_;
        this.proveedor = proveedor;
        this.estante = estante;
    }
    public Dboproducto(String codigo, String codigoSucursal, String codigoAlmacen, String nombre, int cantidad, int stock, int categoria, int unidad, int monedad, int procedencia, BigDecimal precioCosto, BigDecimal precioVenta, double descuento, String estado, Date fecha, String descripcion, BigDecimal final_, int proveedor, int estante) {
       this.codigo = codigo;
       this.codigoSucursal = codigoSucursal;
       this.codigoAlmacen = codigoAlmacen;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.stock = stock;
       this.categoria = categoria;
       this.unidad = unidad;
       this.monedad = monedad;
       this.procedencia = procedencia;
       this.precioCosto = precioCosto;
       this.precioVenta = precioVenta;
       this.descuento = descuento;
       this.estado = estado;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.final_ = final_;
       this.proveedor = proveedor;
       this.estante = estante;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCodigoSucursal() {
        return this.codigoSucursal;
    }
    
    public void setCodigoSucursal(String codigoSucursal) {
        this.codigoSucursal = codigoSucursal;
    }
    public String getCodigoAlmacen() {
        return this.codigoAlmacen;
    }
    
    public void setCodigoAlmacen(String codigoAlmacen) {
        this.codigoAlmacen = codigoAlmacen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }
    public int getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(int unidad) {
        this.unidad = unidad;
    }
    public int getMonedad() {
        return this.monedad;
    }
    
    public void setMonedad(int monedad) {
        this.monedad = monedad;
    }
    public int getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(int procedencia) {
        this.procedencia = procedencia;
    }
    public BigDecimal getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(BigDecimal precioCosto) {
        this.precioCosto = precioCosto;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getFinal_() {
        return this.final_;
    }
    
    public void setFinal_(BigDecimal final_) {
        this.final_ = final_;
    }
    public int getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(int proveedor) {
        this.proveedor = proveedor;
    }
    public int getEstante() {
        return this.estante;
    }
    
    public void setEstante(int estante) {
        this.estante = estante;
    }




}


