package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbosucursal generated by hbm2java
 */
public class Dbosucursal  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String direccion;
     private String telefono;

    public Dbosucursal() {
    }

    public Dbosucursal(String codigo, String nombre, String direccion, String telefono) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


