package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dbotransaccion generated by hbm2java
 */
public class Dbotransaccion  implements java.io.Serializable {


     private Integer id;
     private String codigoCrea;
     private String tipo;
     private BigDecimal monto;
     private Date fecha;
     private String descripcion;
     private String arqueo;
     private String categoria;
     private String documento;
     private String sucursal;
     private int tipoDocu;
     private int credito;
     private int cp;
     private int tipoRango;

    public Dbotransaccion() {
    }

    public Dbotransaccion(String codigoCrea, String tipo, BigDecimal monto, Date fecha, String descripcion, String arqueo, String categoria, String documento, String sucursal, int tipoDocu, int credito, int cp, int tipoRango) {
       this.codigoCrea = codigoCrea;
       this.tipo = tipo;
       this.monto = monto;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.arqueo = arqueo;
       this.categoria = categoria;
       this.documento = documento;
       this.sucursal = sucursal;
       this.tipoDocu = tipoDocu;
       this.credito = credito;
       this.cp = cp;
       this.tipoRango = tipoRango;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigoCrea() {
        return this.codigoCrea;
    }
    
    public void setCodigoCrea(String codigoCrea) {
        this.codigoCrea = codigoCrea;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getArqueo() {
        return this.arqueo;
    }
    
    public void setArqueo(String arqueo) {
        this.arqueo = arqueo;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public int getTipoDocu() {
        return this.tipoDocu;
    }
    
    public void setTipoDocu(int tipoDocu) {
        this.tipoDocu = tipoDocu;
    }
    public int getCredito() {
        return this.credito;
    }
    
    public void setCredito(int credito) {
        this.credito = credito;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public int getTipoRango() {
        return this.tipoRango;
    }
    
    public void setTipoRango(int tipoRango) {
        this.tipoRango = tipoRango;
    }




}


