package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Dbotaller generated by hbm2java
 */
public class Dbotaller  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal precio;

    public Dbotaller() {
    }

    public Dbotaller(String nombre, BigDecimal precio) {
       this.nombre = nombre;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


