package com.avrilco.Entidades;
// Generated 11-15-2017 10:08:00 PM by Hibernate Tools 4.3.1



/**
 * Dbounidad generated by hbm2java
 */
public class Dbounidad  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String abreviatura;

    public Dbounidad() {
    }

    public Dbounidad(String nombre, String abreviatura) {
       this.nombre = nombre;
       this.abreviatura = abreviatura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }




}


