package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="siac"
)
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private Persona persona;
     private String scodigocliente;
     private Boolean bpensionado;
     private Boolean bcomerciante;
     private String sgradodiscapacidad;
     private Float vmontopension;
     private Boolean bempleado;
     private String sempresa;
     private Float vsalario;
     private Set referencias = new HashSet(0);
     private Set ingresos = new HashSet(0);
     private Set solicituds = new HashSet(0);
     private Set egresos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Persona persona) {
        this.persona = persona;
    }
    public Cliente(Persona persona, String scodigocliente, Boolean bpensionado, Boolean bcomerciante, String sgradodiscapacidad, Float vmontopension, Boolean bempleado, String sempresa, Float vsalario, Set referencias, Set ingresos, Set solicituds, Set egresos) {
       this.persona = persona;
       this.scodigocliente = scodigocliente;
       this.bpensionado = bpensionado;
       this.bcomerciante = bcomerciante;
       this.sgradodiscapacidad = sgradodiscapacidad;
       this.vmontopension = vmontopension;
       this.bempleado = bempleado;
       this.sempresa = sempresa;
       this.vsalario = vsalario;
       this.referencias = referencias;
       this.ingresos = ingresos;
       this.solicituds = solicituds;
       this.egresos = egresos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDCLIENTE", unique=true, nullable=false)
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="SCODIGOCLIENTE", length=6)
    public String getScodigocliente() {
        return this.scodigocliente;
    }
    
    public void setScodigocliente(String scodigocliente) {
        this.scodigocliente = scodigocliente;
    }

    
    @Column(name="BPENSIONADO")
    public Boolean getBpensionado() {
        return this.bpensionado;
    }
    
    public void setBpensionado(Boolean bpensionado) {
        this.bpensionado = bpensionado;
    }

    
    @Column(name="BCOMERCIANTE")
    public Boolean getBcomerciante() {
        return this.bcomerciante;
    }
    
    public void setBcomerciante(Boolean bcomerciante) {
        this.bcomerciante = bcomerciante;
    }

    
    @Column(name="SGRADODISCAPACIDAD", length=20)
    public String getSgradodiscapacidad() {
        return this.sgradodiscapacidad;
    }
    
    public void setSgradodiscapacidad(String sgradodiscapacidad) {
        this.sgradodiscapacidad = sgradodiscapacidad;
    }

    
    @Column(name="VMONTOPENSION", precision=10)
    public Float getVmontopension() {
        return this.vmontopension;
    }
    
    public void setVmontopension(Float vmontopension) {
        this.vmontopension = vmontopension;
    }

    
    @Column(name="BEMPLEADO")
    public Boolean getBempleado() {
        return this.bempleado;
    }
    
    public void setBempleado(Boolean bempleado) {
        this.bempleado = bempleado;
    }

    
    @Column(name="SEMPRESA", length=20)
    public String getSempresa() {
        return this.sempresa;
    }
    
    public void setSempresa(String sempresa) {
        this.sempresa = sempresa;
    }

    
    @Column(name="VSALARIO", precision=6)
    public Float getVsalario() {
        return this.vsalario;
    }
    
    public void setVsalario(Float vsalario) {
        this.vsalario = vsalario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(Set referencias) {
        this.referencias = referencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set ingresos) {
        this.ingresos = ingresos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getEgresos() {
        return this.egresos;
    }
    
    public void setEgresos(Set egresos) {
        this.egresos = egresos;
    }




}


