package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,catalog="siac"
)
public class Direccion  implements java.io.Serializable {


     private Integer iddireccion;
     private Persona persona;
     private String sdireccion;

    public Direccion() {
    }

	
    public Direccion(Persona persona) {
        this.persona = persona;
    }
    public Direccion(Persona persona, String sdireccion) {
       this.persona = persona;
       this.sdireccion = sdireccion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDDIRECCION", unique=true, nullable=false)
    public Integer getIddireccion() {
        return this.iddireccion;
    }
    
    public void setIddireccion(Integer iddireccion) {
        this.iddireccion = iddireccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="SDIRECCION", length=100)
    public String getSdireccion() {
        return this.sdireccion;
    }
    
    public void setSdireccion(String sdireccion) {
        this.sdireccion = sdireccion;
    }




}


