package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Egreso generated by hbm2java
 */
@Entity
@Table(name="egreso"
    ,catalog="siac"
)
public class Egreso  implements java.io.Serializable {


     private Integer idegreso;
     private Cliente cliente;
     private String snombre;
     private Float vmonto;
     private Boolean bestado;

    public Egreso() {
    }

	
    public Egreso(Cliente cliente) {
        this.cliente = cliente;
    }
    public Egreso(Cliente cliente, String snombre, Float vmonto, Boolean bestado) {
       this.cliente = cliente;
       this.snombre = snombre;
       this.vmonto = vmonto;
       this.bestado = bestado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDEGRESO", unique=true, nullable=false)
    public Integer getIdegreso() {
        return this.idegreso;
    }
    
    public void setIdegreso(Integer idegreso) {
        this.idegreso = idegreso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="SNOMBRE", length=50)
    public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }

    
    @Column(name="VMONTO", precision=10)
    public Float getVmonto() {
        return this.vmonto;
    }
    
    public void setVmonto(Float vmonto) {
        this.vmonto = vmonto;
    }

    
    @Column(name="BESTADO")
    public Boolean getBestado() {
        return this.bestado;
    }
    
    public void setBestado(Boolean bestado) {
        this.bestado = bestado;
    }




}


