package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="siac"
)
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Persona persona;
     private String sempladoid;
     private String scorreo;
     private String sfoto;
     private Set usuarios = new HashSet(0);
     private Set solicituds = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Persona persona) {
        this.persona = persona;
    }
    public Empleado(Persona persona, String sempladoid, String scorreo, String sfoto, Set usuarios, Set solicituds) {
       this.persona = persona;
       this.sempladoid = sempladoid;
       this.scorreo = scorreo;
       this.sfoto = sfoto;
       this.usuarios = usuarios;
       this.solicituds = solicituds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDEMPLEADO", unique=true, nullable=false)
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="SEMPLADOID", length=10)
    public String getSempladoid() {
        return this.sempladoid;
    }
    
    public void setSempladoid(String sempladoid) {
        this.sempladoid = sempladoid;
    }

    
    @Column(name="SCORREO", length=50)
    public String getScorreo() {
        return this.scorreo;
    }
    
    public void setScorreo(String scorreo) {
        this.scorreo = scorreo;
    }

    
    @Column(name="SFOTO", length=65535)
    public String getSfoto() {
        return this.sfoto;
    }
    
    public void setSfoto(String sfoto) {
        this.sfoto = sfoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


