package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Referencia generated by hbm2java
 */
@Entity
@Table(name="referencia"
    ,catalog="siac"
)
public class Referencia  implements java.io.Serializable {


     private Integer idreferencia;
     private Cliente cliente;
     private Tiporeferencia tiporeferencia;
     private String snombre;
     private Boolean bestado;

    public Referencia() {
    }

	
    public Referencia(Tiporeferencia tiporeferencia) {
        this.tiporeferencia = tiporeferencia;
    }
    public Referencia(Cliente cliente, Tiporeferencia tiporeferencia, String snombre, Boolean bestado) {
       this.cliente = cliente;
       this.tiporeferencia = tiporeferencia;
       this.snombre = snombre;
       this.bestado = bestado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDREFERENCIA", unique=true, nullable=false)
    public Integer getIdreferencia() {
        return this.idreferencia;
    }
    
    public void setIdreferencia(Integer idreferencia) {
        this.idreferencia = idreferencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOREFERENCIA", nullable=false)
    public Tiporeferencia getTiporeferencia() {
        return this.tiporeferencia;
    }
    
    public void setTiporeferencia(Tiporeferencia tiporeferencia) {
        this.tiporeferencia = tiporeferencia;
    }

    
    @Column(name="SNOMBRE", length=50)
    public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }

    
    @Column(name="BESTADO")
    public Boolean getBestado() {
        return this.bestado;
    }
    
    public void setBestado(Boolean bestado) {
        this.bestado = bestado;
    }




}


