package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name="solicitud"
    ,catalog="siac"
)
public class Solicitud  implements java.io.Serializable {


     private Integer idsolicitud;
     private Cliente cliente;
     private Empleado empleado;
     private Tipobanco tipobanco;
     private Tipocredito tipocredito;
     private Tipocuenta tipocuenta;
     private Tipodocumento tipodocumento;
     private Tipogarantia tipogarantia;
     private Tiposolicitud tiposolicitud;
     private String scodigosolicitud;
     private Date dfechasolicitud;
     private String stermino;
     private Float vmonto;
     private Character sformapago;
     private String vcuenta;
     private Double vtasainteres;
     private Date dfechaapertura;
     private Date dfechafinalizacion;
     private Double vtiempolaborado;
     private Float vsalario;
     private String scargo;
     private Short vplazomeses;
     private String sbeneficiario;

    public Solicitud() {
    }

	
    public Solicitud(Empleado empleado, Tiposolicitud tiposolicitud) {
        this.empleado = empleado;
        this.tiposolicitud = tiposolicitud;
    }
    public Solicitud(Cliente cliente, Empleado empleado, Tipobanco tipobanco, Tipocredito tipocredito, Tipocuenta tipocuenta, Tipodocumento tipodocumento, Tipogarantia tipogarantia, Tiposolicitud tiposolicitud, String scodigosolicitud, Date dfechasolicitud, String stermino, Float vmonto, Character sformapago, String vcuenta, Double vtasainteres, Date dfechaapertura, Date dfechafinalizacion, Double vtiempolaborado, Float vsalario, String scargo, Short vplazomeses, String sbeneficiario) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.tipobanco = tipobanco;
       this.tipocredito = tipocredito;
       this.tipocuenta = tipocuenta;
       this.tipodocumento = tipodocumento;
       this.tipogarantia = tipogarantia;
       this.tiposolicitud = tiposolicitud;
       this.scodigosolicitud = scodigosolicitud;
       this.dfechasolicitud = dfechasolicitud;
       this.stermino = stermino;
       this.vmonto = vmonto;
       this.sformapago = sformapago;
       this.vcuenta = vcuenta;
       this.vtasainteres = vtasainteres;
       this.dfechaapertura = dfechaapertura;
       this.dfechafinalizacion = dfechafinalizacion;
       this.vtiempolaborado = vtiempolaborado;
       this.vsalario = vsalario;
       this.scargo = scargo;
       this.vplazomeses = vplazomeses;
       this.sbeneficiario = sbeneficiario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDSOLICITUD", unique=true, nullable=false)
    public Integer getIdsolicitud() {
        return this.idsolicitud;
    }
    
    public void setIdsolicitud(Integer idsolicitud) {
        this.idsolicitud = idsolicitud;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDEMPLEADO", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDBANCO")
    public Tipobanco getTipobanco() {
        return this.tipobanco;
    }
    
    public void setTipobanco(Tipobanco tipobanco) {
        this.tipobanco = tipobanco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOCREDITO")
    public Tipocredito getTipocredito() {
        return this.tipocredito;
    }
    
    public void setTipocredito(Tipocredito tipocredito) {
        this.tipocredito = tipocredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOCUENTA")
    public Tipocuenta getTipocuenta() {
        return this.tipocuenta;
    }
    
    public void setTipocuenta(Tipocuenta tipocuenta) {
        this.tipocuenta = tipocuenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPODOCUMENTO")
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOGARANTIA")
    public Tipogarantia getTipogarantia() {
        return this.tipogarantia;
    }
    
    public void setTipogarantia(Tipogarantia tipogarantia) {
        this.tipogarantia = tipogarantia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOSOLICITUD", nullable=false)
    public Tiposolicitud getTiposolicitud() {
        return this.tiposolicitud;
    }
    
    public void setTiposolicitud(Tiposolicitud tiposolicitud) {
        this.tiposolicitud = tiposolicitud;
    }

    
    @Column(name="SCODIGOSOLICITUD", length=6)
    public String getScodigosolicitud() {
        return this.scodigosolicitud;
    }
    
    public void setScodigosolicitud(String scodigosolicitud) {
        this.scodigosolicitud = scodigosolicitud;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DFECHASOLICITUD", length=19)
    public Date getDfechasolicitud() {
        return this.dfechasolicitud;
    }
    
    public void setDfechasolicitud(Date dfechasolicitud) {
        this.dfechasolicitud = dfechasolicitud;
    }

    
    @Column(name="STERMINO", length=65535)
    public String getStermino() {
        return this.stermino;
    }
    
    public void setStermino(String stermino) {
        this.stermino = stermino;
    }

    
    @Column(name="VMONTO", precision=10)
    public Float getVmonto() {
        return this.vmonto;
    }
    
    public void setVmonto(Float vmonto) {
        this.vmonto = vmonto;
    }

    
    @Column(name="SFORMAPAGO", length=1)
    public Character getSformapago() {
        return this.sformapago;
    }
    
    public void setSformapago(Character sformapago) {
        this.sformapago = sformapago;
    }

    
    @Column(name="VCUENTA", length=10)
    public String getVcuenta() {
        return this.vcuenta;
    }
    
    public void setVcuenta(String vcuenta) {
        this.vcuenta = vcuenta;
    }

    
    @Column(name="VTASAINTERES", precision=22, scale=0)
    public Double getVtasainteres() {
        return this.vtasainteres;
    }
    
    public void setVtasainteres(Double vtasainteres) {
        this.vtasainteres = vtasainteres;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DFECHAAPERTURA", length=19)
    public Date getDfechaapertura() {
        return this.dfechaapertura;
    }
    
    public void setDfechaapertura(Date dfechaapertura) {
        this.dfechaapertura = dfechaapertura;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DFECHAFINALIZACION", length=19)
    public Date getDfechafinalizacion() {
        return this.dfechafinalizacion;
    }
    
    public void setDfechafinalizacion(Date dfechafinalizacion) {
        this.dfechafinalizacion = dfechafinalizacion;
    }

    
    @Column(name="VTIEMPOLABORADO", precision=22, scale=0)
    public Double getVtiempolaborado() {
        return this.vtiempolaborado;
    }
    
    public void setVtiempolaborado(Double vtiempolaborado) {
        this.vtiempolaborado = vtiempolaborado;
    }

    
    @Column(name="VSALARIO", precision=6)
    public Float getVsalario() {
        return this.vsalario;
    }
    
    public void setVsalario(Float vsalario) {
        this.vsalario = vsalario;
    }

    
    @Column(name="SCARGO", length=30)
    public String getScargo() {
        return this.scargo;
    }
    
    public void setScargo(String scargo) {
        this.scargo = scargo;
    }

    
    @Column(name="VPLAZOMESES")
    public Short getVplazomeses() {
        return this.vplazomeses;
    }
    
    public void setVplazomeses(Short vplazomeses) {
        this.vplazomeses = vplazomeses;
    }

    
    @Column(name="SBENEFICIARIO", length=65535)
    public String getSbeneficiario() {
        return this.sbeneficiario;
    }
    
    public void setSbeneficiario(String sbeneficiario) {
        this.sbeneficiario = sbeneficiario;
    }




}


