package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="siac"
)
public class Telefono  implements java.io.Serializable {


     private Integer idtelefono;
     private Persona persona;
     private Tipotelefono tipotelefono;
     private String snumero;

    public Telefono() {
    }

	
    public Telefono(Persona persona, Tipotelefono tipotelefono) {
        this.persona = persona;
        this.tipotelefono = tipotelefono;
    }
    public Telefono(Persona persona, Tipotelefono tipotelefono, String snumero) {
       this.persona = persona;
       this.tipotelefono = tipotelefono;
       this.snumero = snumero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDTELEFONO", unique=true, nullable=false)
    public Integer getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(Integer idtelefono) {
        this.idtelefono = idtelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOTELEFONO", nullable=false)
    public Tipotelefono getTipotelefono() {
        return this.tipotelefono;
    }
    
    public void setTipotelefono(Tipotelefono tipotelefono) {
        this.tipotelefono = tipotelefono;
    }

    
    @Column(name="SNUMERO", length=9)
    public String getSnumero() {
        return this.snumero;
    }
    
    public void setSnumero(String snumero) {
        this.snumero = snumero;
    }




}


