package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotelefono generated by hbm2java
 */
@Entity
@Table(name="tipotelefono"
    ,catalog="siac"
)
public class Tipotelefono  implements java.io.Serializable {


     private Integer idtipotelefono;
     private String snombre;
     private Boolean bestado;
     private Set telefonos = new HashSet(0);

    public Tipotelefono() {
    }

    public Tipotelefono(String snombre, Boolean bestado, Set telefonos) {
       this.snombre = snombre;
       this.bestado = bestado;
       this.telefonos = telefonos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDTIPOTELEFONO", unique=true, nullable=false)
    public Integer getIdtipotelefono() {
        return this.idtipotelefono;
    }
    
    public void setIdtipotelefono(Integer idtipotelefono) {
        this.idtipotelefono = idtipotelefono;
    }

    
    @Column(name="SNOMBRE", length=50)
    public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }

    
    @Column(name="BESTADO")
    public Boolean getBestado() {
        return this.bestado;
    }
    
    public void setBestado(Boolean bestado) {
        this.bestado = bestado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipotelefono")
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }




}


