package com.avrilco.Model;
// Generated 12-24-2017 12:58:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tiporeferencia generated by hbm2java
 */
@Entity
@Table(name="tiporeferencia"
    ,catalog="siac"
)
public class Tiporeferencia  implements java.io.Serializable {


     private Integer idtiporeferencia;
     private String snombre;
     private Boolean bestado;
     private Set referencias = new HashSet(0);

    public Tiporeferencia() {
    }

    public Tiporeferencia(String snombre, Boolean bestado, Set referencias) {
       this.snombre = snombre;
       this.bestado = bestado;
       this.referencias = referencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDTIPOREFERENCIA", unique=true, nullable=false)
    public Integer getIdtiporeferencia() {
        return this.idtiporeferencia;
    }
    
    public void setIdtiporeferencia(Integer idtiporeferencia) {
        this.idtiporeferencia = idtiporeferencia;
    }

    
    @Column(name="SNOMBRE", length=50)
    public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }

    
    @Column(name="BESTADO")
    public Boolean getBestado() {
        return this.bestado;
    }
    
    public void setBestado(Boolean bestado) {
        this.bestado = bestado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiporeferencia")
    public Set getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(Set referencias) {
        this.referencias = referencias;
    }




}


